import type { HomeInspectionCopy } from "./types";

export const homeInspectionEn: HomeInspectionCopy = {
  locale: "en", technicalLocale: "en", route: "/en/home-inspection",
  seo: { title: "Home Inspection in Georgia | Atelier Sweet Home", description: "On-site home inspection before purchase or renovation. Tbilisi, Kakheti and across Georgia. PDF report with photos, from USD 250.", ogTitle: "Home Inspection in Georgia | Atelier Sweet Home", ogDescription: "On-site inspection of a private house before purchase or renovation, with a clear PDF report and photos.", serviceName: "Home Inspection in Georgia", serviceType: "On-site home inspection and pre-purchase property inspection", areaServed: ["Georgia", "Tbilisi", "Kakheti"], availableLanguage: "English" },
  header: { writeLabel: "Book an on-site inspection" },
  hero: { eyebrow: "Tbilisi · Kakheti · across Georgia", title: "Home Inspection for Private Houses in Georgia", lead: "We visit the property and inspect the condition of the house before you buy it or plan a renovation.", body: "We look at the foundations, walls, floors, roof and accessible timber structures. After the visit, you receive a PDF report with photos, a description of the house and a prioritised list of work.", price: "From USD 250", priceQualifier: "for a private house up to 100 m²", onsiteLabel: "On site", optionalPhotos: "You may attach photos if you have them. They help us understand the property before the visit; the inspection itself takes place at the house.", primaryCta: "Book an on-site inspection", secondaryCta: "What we inspect", collageAria: "Old houses and structures at real Atelier Sweet Home properties" },
  scenarios: { title: "When a home inspection is useful", items: [
    { title: "Before buying a house", text: "A pre-purchase home inspection gives you a clearer view of the main structures and the work the house may need after purchase. It is particularly useful for an old house that has stood empty, has been altered by different owners, or shows cracks and signs of damp." },
    { title: "Before renovation", text: "Before planning the work, it helps to understand which parts of the house have remained in good condition, what needs reinforcement and what should be replaced. The inspection findings become the basis for the next stage: a detailed estimate." },
    { title: "When the house has started to change", text: "Cracks, leaning walls, uneven or sagging floors, leaks, damp walls and damaged timber show which parts of the house need attention first." },
    { title: "If you are abroad", text: "You can arrange the inspection remotely. The seller, agent or another person on site can provide access, and you receive the findings in a PDF with photos and explanations." }
  ] },
  onsite: { title: "We inspect the house on site", galleryAria: "Structures at real Atelier Sweet Home properties", paragraphs: [
    "During the visit, we look at the house as a whole, take accessible measurements and compare the condition of its different parts. We check levels and geometry, the pattern of cracks, signs of settlement and moisture, and the condition of the roof, floors and timber elements.",
    "We also renovate and repair old houses ourselves, so we translate what we see into a practical list: what can be preserved, where repairs or reinforcement are needed, and which work should come first.",
    "Photos sent beforehand are additional information. We assess the condition of the house during the inspection at the property."
  ] },
  checklist: { title: "What we inspect", items: [
    { title: "Foundations and settlement", text: "We examine visible parts of the foundations, the position of the house, changes in level, signs of settlement and how these changes relate to cracks in the walls." },
    { title: "Walls and cracks", text: "We assess wall materials and thickness, the pattern of cracks, deviations and the building's geometry, as well as openings and areas that have already been repaired or altered." },
    { title: "Floors, beams and floor structures", text: "We check floor levels, visible deformation and the condition of accessible beams, floors and timber structures." },
    { title: "Roof and roof structure", text: "We inspect the roof covering, rafters, battens and accessible connections. We record leaks, damaged or decayed timber and areas that need repair or replacement." },
    { title: "Damp and leaks", text: "We look for visible signs of moisture, sources of leaks and damage to finishes or structures caused by prolonged damp." },
    { title: "Services and layout", text: "We review accessible utilities and consider how the existing structure relates to the future layout, bathrooms, kitchen and the owner's other plans for the house." }
  ] },
  result: { title: "What you receive after the inspection", intro: "We bring all observations together in one PDF report, which we prepare within 5 working days after the visit. It includes:", items: ["photos of the house and the problem areas found;", "a description of the condition of the parts that were accessible for inspection;", "a prioritised list of necessary work;", "recommendations on what can be preserved;", "which elements should be repaired or reinforced;", "which parts need replacement."], note: "The report helps you decide whether the house is right for you, where to begin and which tasks to include in the next stage.", cta: "Book an on-site inspection" },
  remote: { title: "If you are buying a house from abroad", paragraphs: ["To arrange an inspection, you only need to organise access with the seller or agent. We agree on a date, visit the property, carry out the inspection and send the result to you.", "This gives you an independent view of the house before travelling to Georgia or making a final purchase decision. We can discuss the photos and explanations in the PDF with you remotely."] },
  process: { title: "How it works", steps: [
    { title: "You send an enquiry", text: "Tell us where the house is, its approximate size, why you need the inspection and a convenient time. Photos are optional." },
    { title: "We contact you within 1–2 days", text: "We reply by message or arrange a call, whichever is easier for you. We clarify the task, the location and access to the property." },
    { title: "We arrange the visit", text: "We agree on the date, confirm the inspection price and, when needed, calculate the travel cost to another region in advance." },
    { title: "We inspect the house on site", text: "We visit the property, inspect the accessible parts of the house, take measurements and make photographs for the report." },
    { title: "You receive the PDF", text: "We prepare the report within 5 working days after the visit. It brings together the photos, a description of the house and a prioritised list of necessary work." },
    { title: "You choose the next step", text: "You can use the findings to decide on the purchase or plan the renovation. If needed, we can prepare a detailed estimate as a separate service or discuss specific building work." }
  ] },
  price: { title: "Price and service area", amount: "From USD 250", qualifier: "for a house up to 100 m²", paragraphs: ["The price of inspecting a private house up to 100 m² starts from USD 250. For a larger house, several buildings or an extended scope, we agree the price in advance.", "We work in Tbilisi, Kakheti and across Georgia. For properties in other regions, we calculate the travel cost in advance.", "Once the date and price are agreed, the inspection is paid before the visit."] },
  afterPdf: { title: "What happens after the PDF", paragraphs: ["The PDF is yours to keep and use when deciding what to do with the house. If you need a detailed cost calculation for future work, the next separate stage is an estimate covering quantities, materials, labour and timing. The fee for preparing it depends on the size and complexity of the task and is agreed in advance.", "The inspection may lead to a full or partial renovation, reinforcement of particular structures or a roof replacement. We discuss each decision separately once the condition of the house is clear."], linksAria: "Related services", links: [{ label: "Old house renovation in Georgia", href: "/en/reconstruction" }, { label: "Roof construction and complete roof replacement", href: "/en/roof" }] },
  character: { title: "A practical view of an old house", paragraphs: ["We value old houses for their stone, timber, verandas, proportions and traces of handwork. During an inspection, we look for the elements that have survived well and can continue to serve, and for the areas that now need attention.", "This approach connects the practical list of future work with an understanding of what is worth preserving during renovation."] },
  faq: { title: "Frequently asked questions", items: [
    { question: "Can I book an inspection before buying the house?", answer: "Yes. We arrange access with you, the seller or the agent and inspect the house on site. The PDF helps you understand the condition of the main parts of the house and the likely scope of future work." },
    { question: "Can the inspection take place while I am in another city or country?", answer: "Yes. The seller, agent or another person on site can provide access, and you receive the result remotely." },
    { question: "Can I attach photos before the visit?", answer: "Yes, if you have them. They help us become familiar with the house, while the main information is collected during the on-site visit." },
    { question: "What is included in the PDF report?", answer: "Photos, a description of the condition of the parts accessible for inspection, a prioritised list of necessary work, and recommendations on preserving, repairing, reinforcing or replacing elements. We prepare the report within 5 working days after the visit." },
    { question: "How much does the inspection cost?", answer: "Prices start from USD 250 for a private house up to 100 m². Larger houses, multiple buildings and extended scopes are priced separately." },
    { question: "Do you travel beyond Tbilisi and Kakheti?", answer: "Yes, we work across Georgia. For properties in other regions, we calculate the travel cost in advance." },
    { question: "Is a detailed renovation estimate included in the inspection?", answer: "A detailed estimate is a separate paid stage. We prepare it after the inspection, once the condition of the house and the required work are clear." },
    { question: "Can I hire you for the renovation after the inspection?", answer: "Yes. Based on the PDF, we can discuss specific work, a detailed estimate or a complete house renovation project." }
  ] },
  contact: { title: "Book an on-site home inspection", paragraphs: ["Tell us where the house is and when you would like the inspection to take place. If you know the approximate size, include it in the enquiry. You may attach photos if you have them.", "We will contact you within 1–2 days, clarify the details and arrange the visit."], directAria: "Direct contact details", phoneLabel: "Phone", emailLabel: "Email", form: {
    ariaLabel: "Home inspection enquiry form", heading: "Enquiry form", locationLabel: "Where is the house? — required", areaLabel: "Approximate size — if known", purposeLegend: "Why do you need the inspection? — required", purposes: ["before purchase", "before renovation", "there is a problem with the house", "other"], visitLabel: "When would you like us to visit? — optional", concernLabel: "What are you particularly concerned about? — optional", contactLabel: "How should we contact you? — required", photosLabel: "Photos — optional", selectedFiles: "{count} file(s) selected.", noFiles: "No files selected.", removeFile: "Remove {filename}", attach: "Photos — optional", sending: "Sending…", send: "Send enquiry", responseNote: "We reply within 1–2 days.", required: "Please provide the house location, choose the purpose of the inspection and tell us how to contact you.", fileLimit: "You can attach up to 10 files.", error: "We could not send your enquiry. Please try again or contact us on WhatsApp.", success: "Thank you. Your enquiry has been sent. We will contact you within 1–2 days."
  } },
  images: { stone: { alt: "Old stone house in Georgia", caption: "An old house and its existing structures", altRepeat: "Stone wall of an old private house" }, house: { alt: "Old private house before renovation in Georgia", caption: "The house is considered as a whole during the visit", altRepeat: "Walls and veranda of an old house" }, roof: { alt: "Old roof structure and timber elements", caption: "Accessible roof and timber elements are inspected on site", altRepeat: "Old roof of a house" }, rafters: { alt: "Work on a timber roof structure", caption: "A practical understanding of how old structures are repaired" }, characterCaption: "An old house and its existing structures" },
  footer: { line: "Home inspection for private houses in Georgia", regions: "Tbilisi · Kakheti · across Georgia", copyright: "© 2026 Atelier Sweet Home" }
};
