import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/Header";
import { MessageComposer, type MessageComposerCopy } from "@/components/MessageComposer";
import { ReconstructionHeroCollage, ReconstructionInteriorCollage } from "@/components/ReconstructionPhotoCollages";
import { contactConfig } from "@/data/contacts";

type Locale = "ru" | "en" | "ge";

type Copy = {
  write: string; area: string; title: string; lead: string; heroText: string; heroAction: string;
  inspectionEyebrow: string; inspectionTitle: string; inspectionIntro: string; inspectionVisit: string; inspectionParts: string; inspectionResults: string; inspectionResultText: string; inspectionBudget: string; inspectionNote: string; inspectionAction: string;
  characterEyebrow: string; characterTitle: string; character: string[]; characterPhotos: string;
  responsibilityEyebrow: string; responsibilityTitle: string; responsibility: string[]; remoteTitle: string; remote: string[]; remoteCaption: string;
  roofCaption: string; roofMeta: string; roofText: string;
  projectsEyebrow: string; projectsTitle: string; projects: { title: string; meta: string; text: string; action: string }[];
  alsoEyebrow: string; alsoTitle: string; alsoIntro: string; alsoList: string; roofAction: string; kitchenAction: string; taskAction: string;
  finalEyebrow: string; finalTitle: string; finalText: string; footerLine: string;
  specialist?: { eyebrow: string; title: string; text: string; communication: string };
  composer: MessageComposerCopy; inspectionComposer: MessageComposerCopy;
};

const copies: Record<Locale, Copy> = {
  ru: {
    write: "Связаться с нами", area: "Тбилиси · Кахетия · Грузия", title: "Реконструкция старых домов в Грузии", lead: "Сохраняем старые дома и возвращаем их к жизни.", heroText: "Восстанавливаем старые дома с вниманием к их архитектуре и характеру. Берём на себя весь процесс — от предварительного технического осмотра и проекта до организации работ и готового дома.", heroAction: "Показать дом",
    inspectionEyebrow: "Первый шаг", inspectionTitle: "Предварительный технический осмотр дома", inspectionIntro: "Перед покупкой или реконструкцией важно понять общее состояние дома и масштаб будущих работ.", inspectionVisit: "Наш специалист приезжает на объект и проводит предварительный технический осмотр:", inspectionParts: "фундамент · стены · перекрытия · полы · балки · крыша · окна и двери · следы влаги · инженерные коммуникации", inspectionResults: "По результатам осмотра определяем:", inspectionResultText: "что можно сохранить · что явно требует ремонта или замены · где есть дефекты и риски · какие конструкции требуют более детального обследования.", inspectionBudget: "Вы получаете предварительное понимание состояния дома, основных необходимых работ и ориентировочного масштаба затрат на реконструкцию.", inspectionNote: "Если состояние отдельных конструкций невозможно достоверно определить визуально, мы прямо укажем, что требует дополнительного обследования, вскрытия или технической экспертизы.", inspectionAction: "Заказать предварительный осмотр",
    characterEyebrow: "Подход", characterTitle: "Сохраняем характер старого дома", character: ["В Грузии много красивых старых домов, которые заслуживают новой жизни.", "Мы сохраняем и реставрируем то, что стоит сохранить, укрепляем конструкции и сочетаем старое с современными решениями.", "Так получается красивый, надёжный и удобный дом со своей историей и характером.", "Если вам тоже близок такой подход — давайте вместе придумаем, каким может стать ваш дом."], characterPhotos: "Реальные фотографии деталей дома, процесса восстановления и готовых фрагментов.",
    responsibilityEyebrow: "Организация", responsibilityTitle: "Один ответственный. Весь проект.", responsibility: ["Берём на себя проектирование, смету, план работ, подбор специалистов, закупку материалов, организацию и контроль реконструкции.", "Под конкретные задачи собираем необходимых специалистов и координируем их работу.", "Контролируем качество, последовательность работ, материалы, бюджет, сроки и выполнение согласованных решений."], remoteTitle: "Вы можете находиться за пределами Грузии", remote: ["Можем вести проект, пока вы живёте в другой стране.", "Согласовываем решения и материалы, организуем работу на объекте, отправляем фото- и видеоотчёты, фиксируем расходы и выполненные этапы.", "Такой опыт у нас уже есть — мы вели проект для заказчика, который находился за пределами Грузии.", "Один ответственный за проект, понятная коммуникация и контроль происходящего на объекте."], remoteCaption: "Реальный проект · дистанционное ведение · заказчик находился за пределами Грузии", specialist: { eyebrow: "Специалист", title: "Тимур ведёт осмотр и проект", text: "Тимур — профессиональный строитель с инженерным образованием. Базируется в Кахетии и работает по всей Грузии.", communication: "Связь с клиентом: сообщения, созвоны и отчёты." },
    roofCaption: "Полная реконструкция крыши · реальный объект", roofMeta: "Здесь — реальная фотография выполненной крыши.", roofText: "Иногда состояние старой крыши требует полной замены. Можем демонтировать старую конструкцию, рассчитать и собрать новую стропильную систему и кровлю.",
    projectsEyebrow: "Реальные объекты", projectsTitle: "Реальные объекты", projects: [{ title: "Дом Т", meta: "Восстановление старого дома для круглогодичной жизни · Грузия", text: "Восстановление дома, новая веранда и проёмы, отопление, водоснабжение, электричество, два санузла и внутренняя отделка.", action: "Посмотреть проект →" }, { title: "Полная реконструкция крыши", meta: "Старый частный дом · Грузия", text: "Иногда состояние старой крыши требует полной замены.", action: "Посмотреть проект →" }, { title: "Летняя кухня", meta: "Проект с дистанционным ведением · Грузия", text: "Заказчик находился за пределами Грузии. Согласовывали решения дистанционно, организовывали работы на объекте и показывали заказчику ход проекта.", action: "Посмотреть проект →" }],
    alsoEyebrow: "Другие работы", alsoTitle: "Также можем сделать на участке", alsoIntro: "Вместе с реконструкцией дома или как отдельную работу:", alsoList: "крышу · пристройку · летнюю кухню · навес · баню · хозблок · сарай · забор и другие небольшие постройки и конструкции.", roofAction: "Крыши →", kitchenAction: "Летние кухни →", taskAction: "Обсудить задачу →", finalEyebrow: "Обращение", finalTitle: "Есть старый дом, который хочется восстановить?", finalText: "Давайте посмотрим его и обсудим, что можно сохранить, какие работы потребуются и каким может стать ваш дом.", footerLine: "Реконструкция старых домов в Грузии",
    composer: { message: "Здравствуйте, у меня старый дом в Кахетии, хочу обсудить реконструкцию.", messageLabel: "Сообщение", contactLabel: "Укажите, как с вами связаться", contactPlaceholder: "Email, телефон, WhatsApp или Telegram", attach: "Прикрепить фотографии, документы или ссылку на дом", send: "Отправить →", sending: "Отправляем…", sent: "Сообщение отправлено. Мы свяжемся с вами.", error: "Не удалось отправить сообщение. Попробуйте ещё раз или напишите нам в WhatsApp.", required: "Напишите сообщение и обязательно укажите, как с вами связаться.", remove: "Удалить" },
    inspectionComposer: { message: "Здравствуйте, хочу заказать предварительный технический осмотр дома.", messageLabel: "Сообщение", contactLabel: "Укажите, как с вами связаться", contactPlaceholder: "Email, телефон, WhatsApp или Telegram", attach: "Прикрепить фотографии, документы или ссылку на объявление", send: "Отправить →", sending: "Отправляем…", sent: "Сообщение отправлено. Мы свяжемся с вами.", error: "Не удалось отправить сообщение. Попробуйте ещё раз или напишите нам в WhatsApp.", required: "Напишите сообщение и обязательно укажите, как с вами связаться.", remove: "Удалить" }
  },
  en: {
    write: "Contact us", area: "Tbilisi · Kakheti · Georgia", title: "Old house reconstruction in Georgia", lead: "We preserve old houses and bring them back to life.", heroText: "We restore old houses with attention to their architecture and character. We handle the whole process — from the preliminary technical inspection and design to organising the work and delivering a finished home.", heroAction: "Show your house",
    inspectionEyebrow: "First step", inspectionTitle: "Preliminary technical inspection of a house", inspectionIntro: "Before buying or reconstructing a house, it is important to understand its overall condition and the scale of the future work.", inspectionVisit: "Our specialist visits the property and carries out a preliminary technical inspection:", inspectionParts: "foundation · walls · floors and ceilings · floor structures · beams · roof · windows and doors · signs of moisture · utilities", inspectionResults: "After the inspection, we identify:", inspectionResultText: "what can be preserved · what clearly needs repair or replacement · where defects and risks are present · which structures require more detailed inspection.", inspectionBudget: "You receive a preliminary understanding of the house’s condition, the main work required and the approximate scale of reconstruction costs.", inspectionNote: "If the condition of individual structures cannot be reliably determined visually, we will clearly state what requires additional inspection, opening-up work or technical expertise.", inspectionAction: "Book a preliminary inspection",
    characterEyebrow: "Approach", characterTitle: "Preserving the character of an old house", character: ["Georgia has many beautiful old houses that deserve a new life.", "We preserve and restore what is worth preserving, strengthen structures and combine the old with contemporary solutions.", "The result is a beautiful, reliable and comfortable home with its own history and character.", "If this approach feels right to you, let’s imagine together what your house could become."], characterPhotos: "Real photographs of house details, the restoration process and finished spaces.",
    responsibilityEyebrow: "Organisation", responsibilityTitle: "One person responsible. The whole project.", responsibility: ["We take care of design, estimates, the work plan, selecting specialists, material procurement, organisation and reconstruction supervision.", "We bring together the necessary specialists for each task and coordinate their work.", "We monitor quality, work sequence, materials, budget, schedule and the agreed decisions."], remoteTitle: "You can be outside Georgia", remote: ["We can manage the project while you live in another country.", "We agree on decisions and materials, organise the work on site, send photo and video reports, and record expenses and completed stages.", "We have already done this for a client who was outside Georgia.", "One person responsible for the project, clear communication and control over what is happening on site."], remoteCaption: "Real project · managed remotely · the client was outside Georgia", specialist: { eyebrow: "Specialist", title: "Timur leads the inspection and project", text: "Timur is a professional builder with an engineering education. He is based in Kakheti and works throughout Georgia.", communication: "Client communication: messages, calls and reports." },
    roofCaption: "Full roof reconstruction · real project", roofMeta: "Here is a real photograph of the completed roof.", roofText: "Sometimes the condition of an old roof requires a complete replacement. We can dismantle the old structure, calculate and build a new rafter system and roof.",
    projectsEyebrow: "Real projects", projectsTitle: "Real projects", projects: [{ title: "House T", meta: "Restoration of an old house for year-round living · Georgia", text: "House restoration, a new veranda and openings, heating, water supply, electricity, two bathrooms and interior finishing.", action: "View project →" }, { title: "Full roof reconstruction", meta: "Old private house · Georgia", text: "Sometimes an old roof needs a complete replacement.", action: "View project →" }, { title: "Outdoor kitchen", meta: "Project managed remotely · Georgia", text: "The client was outside Georgia. We agreed on decisions remotely, organised the work on site and shared progress with the client.", action: "View project →" }],
    alsoEyebrow: "Other work", alsoTitle: "We can also build on your property", alsoIntro: "Together with house reconstruction or as a separate project:", alsoList: "a roof · an extension · an outdoor kitchen · a canopy · a bathhouse · an outbuilding · a shed · a fence and other small structures.", roofAction: "Roofs →", kitchenAction: "Outdoor kitchens →", taskAction: "Discuss a project →", finalEyebrow: "Get in touch", finalTitle: "Do you have an old house you would like to restore?", finalText: "Let’s look at it and discuss what can be preserved, what work will be needed and what your house could become.", footerLine: "Old house reconstruction in Georgia",
    composer: { message: "Hello, I have an old house in Kakheti and would like to discuss its reconstruction.", messageLabel: "Message", contactLabel: "How should we contact you?", contactPlaceholder: "Email, phone, WhatsApp or Telegram", attach: "Attach photographs, documents or a link to the property", send: "Send →", sending: "Sending…", sent: "Message sent. We will get in touch with you.", error: "We could not send the message. Please try again or write to us on WhatsApp.", required: "Please write a message and tell us how to contact you.", remove: "Remove" },
    inspectionComposer: { message: "Hello, I would like to arrange a preliminary technical inspection of a house.", messageLabel: "Message", contactLabel: "How should we contact you?", contactPlaceholder: "Email, phone, WhatsApp or Telegram", attach: "Attach photographs, documents or a link to the listing", send: "Send →", sending: "Sending…", sent: "Message sent. We will get in touch with you.", error: "We could not send the message. Please try again or write to us on WhatsApp.", required: "Please write a message and tell us how to contact you.", remove: "Remove" }
  },
  ge: {
    write: "დაგვიკავშირდით", area: "თბილისი · კახეთი · საქართველო", title: "ძველი სახლების რეკონსტრუქცია საქართველოში", lead: "ვინარჩუნებთ ძველ სახლებს და მათ ახალ სიცოცხლეს ვუბრუნებთ.", heroText: "ძველ სახლებს მათი არქიტექტურისა და ხასიათის მიმართ ყურადღებით ვაახლებთ. მთელ პროცესს ვუძღვებით — წინასწარი ტექნიკური დათვალიერებიდან და პროექტიდან სამუშაოების ორგანიზებასა და დასრულებულ სახლამდე.", heroAction: "გვაჩვენეთ სახლი",
    inspectionEyebrow: "პირველი ნაბიჯი", inspectionTitle: "სახლის წინასწარი ტექნიკური დათვალიერება", inspectionIntro: "სახლის შეძენამდე ან რეკონსტრუქციამდე მნიშვნელოვანია მისი საერთო მდგომარეობისა და მომავალი სამუშაოების მასშტაბის გააზრება.", inspectionVisit: "ჩვენი სპეციალისტი ადგილზე მოდის და ატარებს წინასწარ ტექნიკურ დათვალიერებას:", inspectionParts: "საძირკველი · კედლები · გადახურვები · იატაკები · კოჭები · სახურავი · ფანჯრები და კარები · ტენიანობის კვალი · საინჟინრო კომუნიკაციები", inspectionResults: "დათვალიერების შემდეგ ვადგენთ:", inspectionResultText: "რისი შენარჩუნებაა შესაძლებელი · რას სჭირდება აშკარად შეკეთება ან შეცვლა · სად არის დეფექტები და რისკები · რომელ კონსტრუქციებს სჭირდება უფრო დეტალური შემოწმება.", inspectionBudget: "თქვენ იღებთ პირველადი წარმოდგენას სახლის მდგომარეობის, აუცილებელი სამუშაოებისა და რეკონსტრუქციის ხარჯების სავარაუდო მასშტაბის შესახებ.", inspectionNote: "თუ ცალკეული კონსტრუქციების მდგომარეობის ვიზუალურად სანდოდ შეფასება შეუძლებელია, პირდაპირ აღვნიშნავთ, რა საჭიროებს დამატებით დათვალიერებას, გახსნას ან ტექნიკურ ექსპერტიზას.", inspectionAction: "შეუკვეთეთ წინასწარი დათვალიერება",
    characterEyebrow: "მიდგომა", characterTitle: "ვინარჩუნებთ ძველი სახლის ხასიათს", character: ["საქართველოში ბევრი ლამაზი ძველი სახლია, რომელიც ახალ სიცოცხლეს იმსახურებს.", "ვინარჩუნებთ და ვაღდგენთ იმას, რისი შენარჩუნებაც ღირს, ვამაგრებთ კონსტრუქციებს და ძველს თანამედროვე გადაწყვეტილებებს ვუხამებთ.", "ასე მიიღება ლამაზი, საიმედო და კომფორტული სახლი თავისი ისტორიითა და ხასიათით.", "თუ ეს მიდგომა თქვენთვისაც ახლობელია, ერთად წარმოვიდგინოთ, როგორი შეიძლება გახდეს თქვენი სახლი."], characterPhotos: "სახლის დეტალების, აღდგენის პროცესისა და დასრულებული სივრცეების რეალური ფოტოები.",
    responsibilityEyebrow: "ორგანიზება", responsibilityTitle: "ერთი პასუხისმგებელი. მთელი პროექტი.", responsibility: ["ვუძღვებით პროექტირებას, ხარჯთაღრიცხვას, სამუშაო გეგმას, სპეციალისტების შერჩევას, მასალების შესყიდვას, ორგანიზებასა და რეკონსტრუქციის კონტროლს.", "კონკრეტული ამოცანებისთვის ვკრებთ საჭირო სპეციალისტებს და ვაკოორდინირებთ მათ მუშაობას.", "ვაკონტროლებთ ხარისხს, სამუშაოების თანმიმდევრობას, მასალებს, ბიუჯეტს, ვადებსა და შეთანხმებული გადაწყვეტილებების შესრულებას."], remoteTitle: "შეგიძლიათ საქართველოს ფარგლებს გარეთ იყოთ", remote: ["პროექტის მართვა შეგვიძლია, სანამ თქვენ სხვა ქვეყანაში ცხოვრობთ.", "ვათანხმებთ გადაწყვეტილებებსა და მასალებს, ვაორგანიზებთ ადგილზე სამუშაოებს, გიგზავნით ფოტო- და ვიდეოანგარიშებს, ვაფიქსირებთ ხარჯებსა და შესრულებულ ეტაპებს.", "ასეთი გამოცდილება უკვე გვაქვს — პროექტს ვმართავდით კლიენტისთვის, რომელიც საქართველოს ფარგლებს გარეთ იმყოფებოდა.", "ერთი პასუხისმგებელი პროექტზე, გასაგები კომუნიკაცია და ადგილზე მიმდინარე პროცესის კონტროლი."], remoteCaption: "რეალური პროექტი · დისტანციური მართვა · კლიენტი საქართველოს ფარგლებს გარეთ იმყოფებოდა", specialist: { eyebrow: "სპეციალისტი", title: "ტიმური ხელმძღვანელობს დათვალიერებასა და პროექტს", text: "ტიმური — პროფესიონალი მშენებელია საინჟინრო განათლებით. კახეთშია დაფუძნებული და მუშაობს საქართველოს მთელ ტერიტორიაზე.", communication: "კლიენტთან კავშირი: შეტყობინებები, ზარები და ანგარიშები." },
    roofCaption: "სახურავის სრული რეკონსტრუქცია · რეალური ობიექტი", roofMeta: "აქ არის შესრულებული სახურავის რეალური ფოტო.", roofText: "ზოგჯერ ძველი სახურავის მდგომარეობა სრულ შეცვლას მოითხოვს. შეგვიძლია ძველი კონსტრუქციის დემონტაჟი, ახალი კოჭების სისტემისა და სახურავის გამოთვლა და მოწყობა.",
    projectsEyebrow: "რეალური ობიექტები", projectsTitle: "რეალური ობიექტები", projects: [{ title: "სახლი T", meta: "ძველი სახლის აღდგენა მთელი წლის განმავლობაში საცხოვრებლად · საქართველო", text: "სახლის აღდგენა, ახალი ვერანდა და ღიობები, გათბობა, წყალმომარაგება, ელექტროობა, ორი სველი წერტილი და შიდა მოპირკეთება.", action: "ნახეთ პროექტი →" }, { title: "სახურავის სრული რეკონსტრუქცია", meta: "ძველი კერძო სახლი · საქართველო", text: "ზოგჯერ ძველ სახურავს სრული შეცვლა სჭირდება.", action: "ნახეთ პროექტი →" }, { title: "საზაფხულო სამზარეულო", meta: "დისტანციურად მართული პროექტი · საქართველო", text: "კლიენტი საქართველოს ფარგლებს გარეთ იყო. გადაწყვეტილებებს დისტანციურად ვათანხმებდით, ადგილზე ვაორგანიზებდით სამუშაოებს და კლიენტს პროცესს ვუზიარებდით.", action: "ნახეთ პროექტი →" }],
    alsoEyebrow: "სხვა სამუშაოები", alsoTitle: "ასევე შეგვიძლია თქვენს ნაკვეთზე გავაკეთოთ", alsoIntro: "სახლის რეკონსტრუქციასთან ერთად ან ცალკე სამუშაოდ:", alsoList: "სახურავი · მიშენება · საზაფხულო სამზარეულო · ფარდული · აბანო · დამხმარე ნაგებობა · ფარდული · ღობე და სხვა მცირე ნაგებობები და კონსტრუქციები.", roofAction: "სახურავები →", kitchenAction: "საზაფხულო სამზარეულოები →", taskAction: "განვიხილოთ ამოცანა →", finalEyebrow: "მოგვწერეთ", finalTitle: "გაქვთ ძველი სახლი, რომლის აღდგენაც გსურთ?", finalText: "ვნახოთ ის და განვიხილოთ, რის შენარჩუნებაა შესაძლებელი, რა სამუშაოები იქნება საჭირო და როგორი შეიძლება გახდეს თქვენი სახლი.", footerLine: "ძველი სახლების რეკონსტრუქცია საქართველოში",
    composer: { message: "გამარჯობა, კახეთში ძველი სახლი მაქვს და მისი რეკონსტრუქციის განხილვა მსურს.", messageLabel: "შეტყობინება", contactLabel: "როგორ დაგიკავშირდეთ?", contactPlaceholder: "ელფოსტა, ტელეფონი, WhatsApp ან Telegram", attach: "დაამატეთ ფოტოები, დოკუმენტები ან სახლის ბმული", send: "გაგზავნა →", sending: "იგზავნება…", sent: "შეტყობინება გაიგზავნა. დაგიკავშირდებით.", error: "შეტყობინების გაგზავნა ვერ მოხერხდა. სცადეთ თავიდან ან მოგვწერეთ WhatsApp-ზე.", required: "დაწერეთ შეტყობინება და აუცილებლად მიუთითეთ, როგორ დაგიკავშირდეთ.", remove: "წაშლა" },
    inspectionComposer: { message: "გამარჯობა, მსურს სახლის წინასწარი ტექნიკური დათვალიერების შეკვეთა.", messageLabel: "შეტყობინება", contactLabel: "როგორ დაგიკავშირდეთ?", contactPlaceholder: "ელფოსტა, ტელეფონი, WhatsApp ან Telegram", attach: "დაამატეთ ფოტოები, დოკუმენტები ან განცხადების ბმული", send: "გაგზავნა →", sending: "იგზავნება…", sent: "შეტყობინება გაიგზავნა. დაგიკავშირდებით.", error: "შეტყობინების გაგზავნა ვერ მოხერხდა. სცადეთ თავიდან ან მოგვწერეთ WhatsApp-ზე.", required: "დაწერეთ შეტყობინება და აუცილებლად მიუთითეთ, როგორ დაგიკავშირდეთ.", remove: "წაშლა" }
  }
};

const projectImages = ["/images/reconstruction/hero/house-t-restored-clean.png", "/images/roof/projects/roof-after-new-profiled-sheet.jpg", "/images/summer-kitchen/projects/summer-kitchen-yard-wide-view.jpg"];

export function HomePageLayout({ locale }: { locale: Locale }) {
  const c = copies[locale];
  const layoutLabels = locale === "ru"
    ? { remote: "Дистанционно", process: "Последовательность", processTitle: "Как проходит реконструкция", processLine: "Технический осмотр → Проект → Смета и план → Реконструкция → Контроль → Готовый дом" }
    : locale === "en"
      ? { remote: "Remote work", process: "Sequence", processTitle: "How reconstruction works", processLine: "Technical inspection → Design → Estimate and plan → Reconstruction → Supervision → Finished home" }
      : { remote: "დისტანციურად", process: "თანმიმდევრობა", processTitle: "როგორ მიმდინარეობს რეკონსტრუქცია", processLine: "ტექნიკური დათვალიერება → პროექტი → ხარჯთაღრიცხვა და გეგმა → რეკონსტრუქცია → კონტროლი → დასრულებული სახლი" };
  const prefix = locale === "ru" ? "" : `/${locale}`;
  const serviceHref = (path: string) => `${prefix}${path}`;
  return <>
    <Header locale={locale} content={{ brand: "Atelier Sweet Home", writeLabel: c.write }} contacts={contactConfig} activePath="/" />
    <main className={`home-page home-page--${locale}`}>
      <section className="home-station" aria-labelledby="home-title"><div className="home-intro"><p className="eyebrow">{c.area}</p><h1 id="home-title">{c.title}</h1><p className="hero-phrase">{c.lead}</p><p className="hero-text">{c.heroText}</p><a className="primary-button" href="#contact-form">{c.heroAction}</a><p className="home-hero-caption">{c.projects[0].meta}</p></div><ReconstructionHeroCollage houseAlt={c.projects[0].title} interiorAlt={c.characterPhotos} verandaAlt={c.projects[0].title} /></section>
      <section className="home-inspection" id="inspection"><div className="home-inspection__copy"><p className="eyebrow">{c.inspectionEyebrow}</p><h2>{c.inspectionTitle}</h2><p>{c.inspectionIntro}</p><p>{c.inspectionVisit}</p><p className="home-emphasis">{c.inspectionParts}</p><p>{c.inspectionResults}</p><p className="home-emphasis">{c.inspectionResultText}</p><p>{c.inspectionBudget}</p><p className="home-note">{c.inspectionNote}</p><p>{c.inspectionAction}</p></div><div><a className="home-whatsapp" href={contactConfig.whatsapp}>WhatsApp</a><MessageComposer copy={c.inspectionComposer} pageTitle={c.inspectionTitle} /></div></section>
      {c.specialist ? <section className="section home-specialist"><p className="eyebrow">{c.specialist.eyebrow}</p><h2>{c.specialist.title}</h2><p>{c.specialist.text}</p><p className="home-emphasis">{c.specialist.communication}</p></section> : null}
      <section className="section home-character"><div className="section-heading"><p className="eyebrow">{c.characterEyebrow}</p><h2>{c.characterTitle}</h2></div><div className="home-character__body"><div>{c.character.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className="home-photo-caption">{c.characterPhotos}</p></div></div></section>
      <ReconstructionInteriorCollage verandaAlt={c.projects[0].title} plantsAlt={c.characterPhotos} buffetAlt={c.characterPhotos} />
      <section className="section home-responsibility"><article><p className="eyebrow">{c.responsibilityEyebrow}</p><h2>{c.responsibilityTitle}</h2>{c.responsibility.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</article><article><p className="eyebrow">{layoutLabels.remote}</p><h2>{c.remoteTitle}</h2>{c.remote.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<p className="home-remote-caption">{c.remoteCaption}</p></article></section>
      <section className="home-process"><p className="eyebrow">{layoutLabels.process}</p><h2>{layoutLabels.processTitle}</h2><p>{layoutLabels.processLine}</p></section>
      <section className="section home-projects"><div className="section-heading"><p className="eyebrow">{c.projectsEyebrow}</p><h2>{c.projectsTitle}</h2></div><div className="home-projects__grid">{c.projects.map((project, index) => <Link href={serviceHref(["/reconstruction", "/roof", "/summer-kitchen"][index])} key={project.title}><figure><Image src={projectImages[index]} alt={project.title} width={980} height={700} sizes="(max-width: 980px) 100vw, 32vw" /></figure><h3>{project.title}</h3><p className="project-meta">{project.meta}</p><p>{project.text}</p><span>{project.action}</span></Link>)}</div></section>
      <section className="section home-also"><div className="section-heading"><p className="eyebrow">{c.alsoEyebrow}</p><h2>{c.alsoTitle}</h2></div><div><p>{c.alsoIntro}</p><p className="home-emphasis">{c.alsoList}</p><div className="hero-actions"><Link className="primary-button" href={serviceHref("/roof")}>{c.roofAction}</Link><Link className="secondary-link" href={serviceHref("/summer-kitchen")}>{c.kitchenAction}</Link><a className="secondary-link" href="#contact-form">{c.taskAction}</a></div></div></section>
      <section className="section home-final" id="contact-form"><div><p className="eyebrow">{c.finalEyebrow}</p><h2>{c.finalTitle}</h2><p>{c.finalText}</p><a className="home-whatsapp" href={contactConfig.whatsapp}>WhatsApp</a></div><MessageComposer copy={c.composer} pageTitle={c.finalTitle} /></section>
    </main>
    <footer className="site-footer"><div><strong>Atelier Sweet Home</strong><span>{c.footerLine}</span><span>{c.area}</span></div><div className="footer-meta"><span>RU / EN / GE</span><span>© 2026 Atelier Sweet Home</span></div></footer>
  </>;
}
